/**
 * get list: getlist, getlist success, getlist fail
 */

export const GETUSERLIST = "HOMEMANAGEMENT/GETUSERLIST";
export const GETUSERLIST_SUCCESS = "HOMEMANAGEMENT/GETUSERLIST_SUCCESS";
export const GETUSERLIST_FAIL = "HOMEMANAGEMENT/GETUSERLIST_FAIL";
