/**
 * get list: getlist, getlist success, getlist fail
 */

export const GETUSERLIST = "HEADERMANAGEMENT/GETUSERLIST";
export const GETUSERLIST_SUCCESS = "HEADERMANAGEMENT/GETUSERLIST_SUCCESS";
export const GETUSERLIST_FAIL = "HEADERMANAGEMENT/GETUSERLIST_FAIL";

export const SIGNIN = "HEADERMANAGEMENT/SIGNIN";
export const SIGNIN_SUCCESS = "HEADERMANAGEMENT/SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "HEADERMANAGEMENT/SIGNIN_FAIL";
